### ISSUE TITLE
Establish output data format

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/mapbox-geostats#1]
I'm taking [tile-stat-stream's output](https://github.com/mapbox/tile-stat-stream#output) as a starting point. But I have plenty of questions. I will try to answer them by looking at the end use-case of these stats, in Studio, and poking around in other places.

- What do we do about fields that have both numeric and non-numeric values?
- Are there any statistics to generate for non-numeric values?
- At what point do we cut off the `fields` list, and what's the right way to communicate that to the user?
- At what point do we cut off any given `values` list (or all `values` lists?), and, again, what's the right way to communicate that to the user?
- Since geojson and shapefile data will not have layers (I think?), do we generate an object with `geometryTypes` etc. at the top-level, or add one level with a fake "layer name" (probably derived from the filename"?
- How do we handle non-primitive field values (objects, arrays)?

**Comment by davidtheclark** [comment]
Looking at the tile-stat-stream, code, I have a couple of questions maybe @tmcw or @rclark can answer:

- Why does tile-stat-stream limit *unique* values per field, instead just values per field? https://github.com/mapbox/tile-stat-stream/blob/master/index.js#L101
- Looks like tile-stat-stream cuts off string values longer than 256 — why not truncate? https://github.com/mapbox/tile-stat-stream/blob/master/index.js#L89
- Is there currently no cut-off for fields? That is, if there are 10 million unique fields in the data, the stats will try to output all of them? Or am I missing the cut-off? @rclark suggested yesterday that this cut-off would be important, which makes sense to me.

**Comment by rclark** [comment]
Let's consider cutoff of all sorts like:
- Document the limit for each list that has a max length (num fields and num values, right?)
- Provide a count of the total number of either of these things

So an output could tell you that there are 1234 total unique values in a particular field, but the list of values only gives you 100. Would there be some meaningful way to say *which* 100 will be in the list?

Layer names: Using the filename for geojson should be fine.

Non-primitive: Let's call these out as a unique field type and not collect any statistics or unique values.

Mix-and-match fields: Can we fall back to `string` in these cases?

> limit unique values per field, instead just values per field?

We're only interested in collecting a list of unique values, not a list with duplicates in it.

> cuts off string values longer than 256 — why not truncate?

Strings longer than 256 characters are very likely to be descriptive, and not useful for layer filtering or data-driven styling.

**Comment by davidtheclark** [comment]
Right now I have these limits set:

- max fields that get counted: 1000
- max fields that get listed and detailed: 100
- max values per field that get counted: 1000
- max values per field that get listed: 100

I don't know yet of any meaningful way to determine which would make it into the list, besides the first ones encountered.

I have a layer name drawn from the file name (basename minus extname).

Turns out gdal and mapnik do not reliably provide non-primitives in their original form (gdal stringifies objects, mapnik stringifies arrays and objects), so we will just stringify them and not worry about it.

If a field has any non-numeric value, its numeric stats (min, max, sum) will be deleted. Mixed values will still be listed together, e.g. `values: [ 1, 'something', true ]`.

I'm experimenting with truncating strings longer than 256 at 50 chars with an ellipsis. Don't know if that's useful or not.

**Comment by rclark** [comment]
I don't think you should bother truncating. Long strings likely don't represent any sort of feature classification, which is the goal of this whole ordeal in the first place.

Other than that this sounds perfect.

**Comment by davidtheclark** [comment]
> I don't think you should bother truncating. Long strings likely don't represent any sort of feature classification, which is the goal of this whole ordeal in the first place.

Ok.

**Comment by davidtheclark** [comment]
Spoke with @rclark and @samanpwbb today about what we're aiming at, and decided on some changes.

The format will be tailored to match that of the tilestats API response, and there will be congruity between what this tool outputs, what the API consumes, and what the API returns. 

(The API will need to be altered anyway to accept all the stats in a single chunk, which this tool will create, instead of piecing together multiple chunks from multiple processes on multiple servers, as it is doing now with `tile-stat-stream` working as tiles are being created in parallel.)

Instead of modifying `tile-stat-stream` and duplicating a lot of logic between this tool and that one, we can just leave it as-is and build a tile interpreter into this library.

**Comment by davidtheclark** [comment]
Output is established for now and schematized in https://github.com/mapbox/mapbox-geostats/blob/master/output-schema.json
