### ISSUE TITLE
mapbox-geostats does not exit immediately after printing stats

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mapbox-geostats#34]
To replicate:

  - Use latest mapbox-geostats
  - Run it on an mbtiles file created with tippecanoe that includes `tilestats`

Expected behavior is for the command to exit immediately after the JSON stats are printed.

The actual behavior I am seeing is that the command continues to run and the stream continues to process tiles.

/cc @mapbox/unpacker 

Refs #33

**Comment by mapsam** [comment]
Thanks for raising @springmeyer - looks like we are [resolving this promise](https://github.com/mapbox/mapbox-geostats/blob/master/lib/tile-analyze.js#L73) as expected, but code execution continues unless we explicitly `return resolve()`. I'll get a quick fix out!
