### ISSUE TITLE
How to count (unique) features in MBTiles files?

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/mapbox-geostats#5]
These two counts are supposed to be the same, because they represent the same data: 

- https://github.com/mapbox/mapbox-geostats/blob/master/test/fixtures/expected/simple-geojson.json#L6
- https://github.com/mapbox/mapbox-geostats/blob/master/test/fixtures/expected/simple-mbtiles.json#L6

The difference is that `simple-mbtiles` is derived from an MBTiles file. I'm assuming that this high number means that the 8 features from the original GeoJSON (which I converted to MBTiles) were found in multiple tiles, so continually reanalyzed and added to the count.

The big question: *Is there any way to accurately determine that a feature has already been checked?*

If not, I guess we'll have to accept that feature count is meaningless for MBTiles files. We may want to remove it from the stats.

**Comment by rclark** [comment]
> Is there any way to accurately determine that a feature has already been checked?

Nope. Sometimes feature's will have IDs in the vector tiles, but it is not required. Nor is it required that the IDs actually correlate features across the various tiles in a tileset. You could build an mbtiles file this way, but you don't have to, and usually you don't see them built like this.

I think you should include the feature count though, still. This is not really a meaningless metric -- its still some information about the complexity of the tileset as a whole.

**Comment by davidtheclark** [comment]
OK, I will just modify the caveat in the readme.
