### ISSUE TITLE
Limit layer and attribute names to 256 characters

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/mapbox-geostats#6]
Attribute value strings are limited to 256 characters. Although we are unlikely to run up against layer and attribute names longer than that, we should write the code that anticipates it. Since these values do need names, and they need to be unique, I think we will have to try truncating the string; and if the truncated version matches an existing truncated version, maybe truncate it another character (?).

I believe that layer and attribute names are the only other strings (other than attribute values) that we'll have to worry about.

**Comment by rclark** [comment]
:+1: sounds like a good idea.

**Comment by davidtheclark** [comment]
This is now done, but a little more crudely. We're just truncating layer and attribute names at 256 characters, and treating any names that start with the same 256 characters as the same name. Caveat: if your strings only differ after the 256th character, you'll have a slightly weird result.

**Comment by davidtheclark** [comment]
https://github.com/mapbox/mapbox-geostats#limitations
